version: '3.8'

services:
  app:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: src/app/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env

  postgres:
    restart: always
    build: 
      context: .
      dockerfile: database/Dockerfile
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports: 
      - "5433:5432"
    