// [layout.jsx]
import { Inter } from "next/font/google";
import "./globals.css";
import SideNav from "./ui/sideNav";
import SideEditor from "./ui/sideEditor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-100 text-slate-900">
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <SideNav />
          <div className="flex-grow p-6 md:overflow-y-auto md:p-12">
            {children}
          </div>
          <SideEditor />
        </div>
      </body>
    </html>
  );
}
